// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cryptocurrency struct {
	ID              string
	Symbol          string
	Name            string
	CurrentPriceUsd string
	CurrentPriceEur string
	DescriptionEn   string
	UpdatedAt       time.Time
}

type Transaction struct {
	ID         uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Amount     string
	ExecutedAt time.Time
}

type User struct {
	ID        uuid.UUID
	UserName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  string
}

type Wallet struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	CryptoTypeID string
	BalanceUsd   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
