// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: wallets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (id, owner_id, crypto_type_id, balance_usd, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, crypto_type_id, balance_usd, created_at, updated_at
`

type CreateWalletParams struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	CryptoTypeID string
	BalanceUsd   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet,
		arg.ID,
		arg.OwnerID,
		arg.CryptoTypeID,
		arg.BalanceUsd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CryptoTypeID,
		&i.BalanceUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
