name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
    tests:
      name: Tests
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4.1.6

        - name: Set up go
          uses: actions/setup-go@v5.0.1
          with:
            go-version: '1.22.2'

        - name: Test
          run: go test ./...

        - name: Install gosec
          run: go install github.com/securego/gosec/v2/cmd/gosec@latest
        
        - name: Use gosec
          run: gosec ./...
        
    style:
        name: Style
        runs-on: ubuntu-latest
    
        steps:
          - name: Check out code
            uses: actions/checkout@v4.1.6

          - name: Set up go
            uses: actions/setup-go@v5.0.1
            with:
                go-version: '1.22.2'
            
          - name: Format go
            run: go fmt ./...

          - name: Install staticcheck
            run: go install honnef.co/go/tools/cmd/staticcheck@latest
        
          - name: Run staticcheck
            run: staticcheck ./...
    